#### Exclude
exclude: [".rvmrc", ".rbenv-version", "README.md", "README_en.md", "Rakefile", "changelog.md"]

#### Code Highlighter
# 'pygments' is unsupported on GitHub Pages now.
highlighter: rouge

#### Permalink
# For more see: http://jekyllrb.com/docs/permalinks/
permalink: pretty

#### Markdown Processors
# 'redcarpet' is unsupported on GitHub Pages now.
markdown: kramdown
kramdown:
    input: GFM

#### Default Attributes
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

#### Pagination
paginate: 20

#### Site
title : (｢･ω･)｢٩( 'ω' )و
tagline: 朝碧海而暮苍梧，睹青天而攀白日
assets: /assets
url:
baseurl:

#### Language
language: zh-CN
## blog site languages: en, zh-CN, zh-TW, de

#### Menu
menu:
  Home: /
  categories: /categories
  tags: /tags
  Archives: /archives
  About: /about
## you can create `tags` and `categories` folders (I had created them already).
## And create a `index.md` file in each of them.
## set `front-matter`as
## layout: tags (or categories)
## title: tags (or categories)
## ---

#### Widgets
widgets:
- category
- tag
- tagcloud
- links
## - douban
## - github-card
## - rss
## provide seven widgets:github-card,category,tag,rss,archive,tagcloud,links,weibo,douban


#### RSS
rss: /atom.xml ## RSS address.

#### Image
imglogo:
  enable: true             ## display image logo true/false.
  src: img/logo.svg        ## `.svg` and `.png` are recommended.
favicon: img/favicon.ico   ## size:32px*32px,`.ico` is recommended.
apple_icon: img/logo.svg ## size:114px*114px.
author_img: img/author.jpg ## size:220px*220px.display author avatar picture.if don't want to display,please don't set this.
banner_img: img/banner.jpg ## size:1920px*200px+. Banner Picture

#### index post is expanding or not
index:
  expand: true           ## default is unexpanding,so you can only see the short description of each post.
  excerpt_link: Read More

close_aside: false  #close sidebar in post page if true
mathjax: true       #enable mathjax if true
share_to: true      #enable share-to buttons if true

#### Author information
author:
  name: quantpengpeng
  intro_line1:  万般皆是心，点点皆由人    ## your introduction on the bottom of the page
  intro_line2:    ## the 2nd line
  weibo:      ## e.g. XXX for http://weibo.com/XXX
  weibo_verifier:  ## e.g. XXX Your weibo-show widget verifier ,if you use weibo-show it is needed.
  tsina:      ## e.g. XXX  Your weibo ID,It will be used in share button.
  douban:     ## e.g. XXX or your id for https://www.douban.com/people/XXX
  zhihu:      ## e.g. XXX  for http://www.zhihu.com/people/XXX
  email:      quantpengpeng@outlook.com ## e.g. XXX@gmail.com
  twitter:    ## e.g. XXX for https://twitter.com/XXX
  github:     QuantPengPeng ## e.g. QuantPengPeng for https://github.com/QuantPengPeng
  facebook:   ## e.g. XXX for https://facebook.com/XXX
  linkedin:   ## e.g. XXX for https://www.linkedin.com/in/XXX
  google_plus:    ## e.g. "XXX" for https://plus.google.com/u/0/XXX, the "" is needed!
  stackoverflow:  ## e.g. XXX for http://stackoverflow.com/users/XXX/jark
## if you set them, the corresponding  share button will show on the footer

#### Toc
toc:
  article: true   ## show contents in article.
  aside: true     ## show contents in aside.
## you can set both of the value to true of neither of them.
## if you don't want display contents in a specified post,you can modify `front-matter` and add `toc: false`.

#### Links
links:
  GDPU: https://www.gdpu.edu.cn/
  GDOU: https://dxxy.gdou.edu.cn/
  Deloitte: https://www2.deloitte.com/cn/zh.html
  CATL: https://www.catl.com/

#### Comment
duoshuo_shortname:
disqus_shortname:
hypercomments_id:
yungentie_productkey:
## set only one of them

#### Share button
jiathis:
  enable: false
  id:
  tsina:

#### Analytics
google_analytics:
  enable: false
  id:
  site:
baidu_tongji:
  enable: false
  sitecode:
cnzz_tongji:
  enable: false
  siteid:

#### Miscellaneous
fancybox: true        ## if you use gallery post or want use fancybox please set the value to true.
totop: true           ## if you want to scroll to top in every post set the value to true

#### Custom Search
google_cse:
  enable: false
  cx:
baidu_search:
  enable: false
  id:
  site:
tinysou_search:
  enable: false
  id:
simple_jekyll_search:
  enable: true
  fulltext: true

gems:
 - jemoji
